<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:tns="urn:arnleadservicewsdl"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="urn:usuarioservicewsdl">

    <types>
        <xsd:schema targetNamespace="urn:usuariowsdl">
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
        </xsd:schema>
    </types>

    <message name="usuarioRequest">
        <part name="nombre" type="xsd:string" />
        <part name="celular" type="xsd:string" />
        <part name="correo" type="xsd:string" />
        <part name="numeroIdentificacion" type="xsd:string" />
    </message>

    <message name="usuarioResponse">
        <part name="return" type="xsd:string" />
    </message>

    <portType name="usuariowsdlPortType">
        <operation name="crearusuario">
            <documentation>usuario World</documentation>
            <input message="tns:usuarioRequest"/>
            <output message="tns:usuarioResponse"/>
        </operation>
    </portType>

    <binding name="usuariowsdlBinding" type="tns:usuariowsdlPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="crearusuario">
            <soap:operation soapAction="urn:arnleadservicewsdl#crearusuario" style="rpc"/>

            <input>
                <soap:body use="encoded" namespace="urn:usuariowsdl"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>

            <output>
                <soap:body use="encoded" namespace="urn:usuariowsdl"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <service name="usuariowsdl">
        <port name="usuariowsdlPort" binding="tns:usuariowsdlBinding">
            <soap:address location="http://soap.payco.com/usuario/soap" />
        </port>
    </service>
</definitions>